version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building Spring Boot project..."
      - mvn clean package

artifacts:
  files:
    - target/*.war
    - appspec.yml
  discard-paths: yes